#!/bin/bash

DIR=$1
ORIGIN=$(pwd)

cd $DIR

source load-nvm .

if [ -f 'yarn.lock' ]; then
    NPM_CLIENT="yarn"
else
    NPM_CLIENT="npm"
fi

echo "Installing dependencies..."
eval "$NPM_CLIENT install --verbose"

if [ -f 'lerna.json' ]; then
    lerna bootstrap
fi

echo "Transpiling typescript..."
eval "$NPM_CLIENT run transpile"

cd $ORIGIN
