#!/bin/bash

do_help() {
    echo "Help for RISE Node Container:"
    echo -e "\tstart                    | alias for 'manager start all'"
    echo -e "\tmanager [command] <args> | access manager.sh"
}

start_all() {
    ./manager.sh start all
    tail -f logs/*
}

ORIGIN=$(pwd)
cd out

case $1 in
    "start")
        start_all
        ;;
    "dev")
        cd src
        BOOTSTRAP="$HOME/bootstrap.sh $HOME/out/src"
        SHELL=/bin/sh chokidar "{,!(node_modules)/**/}package.json" -p -c $BOOTSTRAP &
        eval $BOOTSTRAP
        cd ../
        start_all
        ;;
    "manager")
        ./manager.sh "${@:2}"
        ;;
    *)
        do_help
        ;;
esac

cd $ORIGIN
