#!/bin/bash

do_help() {
    echo "Help for RISE Node Container:"
    echo -e "\tstart                    | alias for 'manager start all'"
    echo -e "\tmanager [command] <args> | access manager.sh"
}

start_all() {
    source load-nvm ./src
    ./manager.sh start all
    tail -f logs/*
}

POSITIONAL=()
WATCH="NO"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -w|--watch)
    WATCH="YES"
    shift
    ;;
    *)
    POSITIONAL+=("$1")
    shift
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

ORIGIN=$(pwd)
cd $HOME/out

case $1 in
    "start")
        start_all
        ;;
    "dev")
        cd src
        BOOTSTRAP="bootstrap-node $HOME/out/src"
        source $BOOTSTRAP
        if [ $WATCH = "YES" ]; then
            echo "Bootstrapping node on dependency changes..."
            SHELL=/bin/sh chokidar "$HOME/out/src/{,!(node_modules)/**/}package.json" -p -c "$BOOTSTRAP" &
        fi
        cd ../
        start_all
        ;;
    "script")
        source load-nvm ./src
        ./manager.sh start db 2>&1 >/dev/null
        ./manager.sh start redis 2>&1 >/dev/null
        cd ./src
        cat ./.scripts/script.js | node - "${@:2}" 2> /dev/null
        ;;
    "manager")
        ./manager.sh "${@:2}"
        ;;
    *)
        do_help
        ;;
esac

cd $ORIGIN
